### ISSUE TITLE
AttributeError: module 'ankisyncd.config' has no attribute 'load'

### ISSUE THREAD

**Issue by AutomaticUpdates** [ankicommunity/anki-sync-server#153]
When trying to run `python -m ankisyncd_cli adduser username` the following error occurs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anki-sync-server/src/ankisyncd_cli/__main__.py", line 1, in <module>
    from ankisyncd_cli import ankisyncctl
  File "/opt/anki-sync-server/src/ankisyncd_cli/ankisyncctl.py", line 10, in <module>
    config = config.load()
AttributeError: module 'ankisyncd.config' has no attribute 'load'
```
I use the `develop` branch

**Comment by VikashKothary** [comment]
Sorry about this. I renamed the method and forgot to update it in the CLI. Will fix in the next few hours.

**Comment by VikashKothary** [comment]
I've pushed a fix. Can you try now?

**Comment by AutomaticUpdates** [comment]
It works now, thanks!
