### ISSUE TITLE
同步失败: Traceback (most recent call last):   File "aqt\sync.py", line 382, in _sync

### ISSUE THREAD

**Issue by maxwellhouse102** [ankicommunity/anki-sync-server#60]
同步失败:
Traceback (most recent call last):
  File "aqt\sync.py", line 382, in _sync
  File "aqt\sync.py", line 362, in _abortingSync
  File "anki\sync.py", line 42, in sync
  File "anki\sync.py", line 594, in meta
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by VikashKothary** [comment]
Hi @maxwellhouse102,

Could you provide more information on we could reproduce this issue?
